version: '3'
services:
  wasp-checker:
    build: .
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - USE_ELK=true
    ports:
      - "8001:80"
  mongodb:
    image: mongo
